version: '3'

services:
  nodejs: 
    image: node:16.3.0-alpine
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: nodejs
    ports:
      - '3000:3000'
    links:
     - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data:/data/db
    expose:
     - 27017